// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP str_rev( SEXP x );
SEXP _biox_dimer(SEXP s1SEXP, SEXP s2SEXP);
SEXP _biox_dimer_v(SEXP ss1SEXP, SEXP ss2SEXP);
SEXP _biox_dimer_test(SEXP ssSEXP, SEXP cutoffSEXP);
SEXP _biox_dimer_tm_v(SEXP ss1SEXP, SEXP ss2SEXP);
SEXP _biox_read_fa(SEXP fileSEXP);
SEXP _biox_read_fq(SEXP fileSEXP);
SEXP _biox_kmers(SEXP sSEXP, SEXP binSEXP, SEXP stepSEXP);
SEXP _biox_kmers_tm(SEXP sSEXP, SEXP t0SEXP, SEXP dtSEXP);
SEXP _biox_rdna(SEXP nSEXP, SEXP lSEXP);
SEXP _biox_int2seq(SEXP numSEXP, SEXP lenSEXP);
SEXP _biox_dnas(SEXP lSEXP);
SEXP _biox_rrna(SEXP nSEXP, SEXP lSEXP);
SEXP _biox_rpro(SEXP nSEXP, SEXP lSEXP);
SEXP _biox_revcomp(SEXP ssSEXP);
SEXP _biox_transcribe(SEXP ssSEXP);
SEXP _biox_translate(SEXP ssSEXP, SEXP offsetSEXP);
SEXP _biox_tm(SEXP ssSEXP);

R_CallMethodDef callMethods[]  = {
  {"Cstr_rev", (DL_FUNC) &str_rev, 1},
  {"C_biox_dimer", (DL_FUNC) &_biox_dimer, 2},
  {"C_biox_dimer_v", (DL_FUNC) &_biox_dimer_v, 2},
  {"C_biox_dimer_test", (DL_FUNC) &_biox_dimer_test, 2},
  {"C_biox_dimer_tm_v", (DL_FUNC) &_biox_dimer_tm_v, 2},
  {"C_biox_read_fa", (DL_FUNC) &_biox_read_fa, 1},
  {"C_biox_read_fq", (DL_FUNC) &_biox_read_fq, 1},
  {"C_biox_kmers", (DL_FUNC) &_biox_kmers, 3},
  {"C_biox_kmers_tm", (DL_FUNC) &_biox_kmers_tm, 3},
  {"C_biox_rdna", (DL_FUNC) &_biox_rdna, 2},
  {"C_biox_int2seq", (DL_FUNC) &_biox_int2seq, 2},
  {"C_biox_dnas", (DL_FUNC) &_biox_dnas, 1},
  {"C_biox_rrna", (DL_FUNC) &_biox_rrna, 2},
  {"C_biox_rpro", (DL_FUNC) &_biox_rpro, 2},
  {"C_biox_revcomp", (DL_FUNC) &_biox_revcomp, 1},
  {"C_biox_transcribe", (DL_FUNC) &_biox_transcribe, 1},
  {"C_biox_translate", (DL_FUNC) &_biox_translate, 2},
  {"C_biox_tm", (DL_FUNC) &_biox_tm, 1},
  {NULL, NULL, 0}
};

void R_init_biox(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

