# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' dimer
#' @export
#' @examples
#' dimer("AG", "CT")
#' dimer("AG", "CCCT")
#' dimer("AG", "CTCC")
#' dimer("CCCT", "AG")
dimer <- function(s1, s2) {
    .Call(`_biox_dimer`, s1, s2)
}

#' @export
dimer_v <- function(ss1, ss2) {
    .Call(`_biox_dimer_v`, ss1, ss2)
}

#' @export
dimer_test <- function(ss, cutoff = 18.0) {
    .Call(`_biox_dimer_test`, ss, cutoff)
}

#' @export
dimer_tm_v <- function(ss1, ss2) {
    .Call(`_biox_dimer_tm_v`, ss1, ss2)
}

read_fa <- function(file) {
    .Call(`_biox_read_fa`, file)
}

read_fq <- function(file) {
    .Call(`_biox_read_fq`, file)
}

#' kmers
#' @param s seq
#' @param bin kmer count size
#' @param step kmer count step
#' @examples
#' kmers("AGCTTTTTTTTT")
#' kmers("AGCTTTTTTTTT", 4)
#' 
#' @export
kmers <- function(s, bin = 3L, step = 1L) {
    .Call(`_biox_kmers`, s, bin, step)
}

#' get kmers by tm range
#' @export
#' @param s seq
#' @param t0 kmer tm
#' @param dt kmer tm range
#' @examples
#' kmers_tm("AGCTTTTTTTTT", 8)
kmers_tm <- function(s, t0, dt = 1) {
    .Call(`_biox_kmers_tm`, s, t0, dt)
}

#' @export
rdna <- function(n = 1L, l = 20L) {
    .Call(`_biox_rdna`, n, l)
}

#' @export
int2seq <- function(num, len) {
    .Call(`_biox_int2seq`, num, len)
}

#' @export
dnas <- function(l) {
    .Call(`_biox_dnas`, l)
}

#' @export
rrna <- function(n = 1L, l = 20L) {
    .Call(`_biox_rrna`, n, l)
}

#' @export
rpro <- function(n = 1L, l = 20L) {
    .Call(`_biox_rpro`, n, l)
}

#' reverse complement seq
#' @param ss seq vectors
#' @examples
#' revcomp(c("AGCT", "AAAA"))
#' 
#' @export
revcomp <- function(ss) {
    .Call(`_biox_revcomp`, ss)
}

#' transcription, from DNA to RNA
#' @examples
#' transcribe("AGCT") # "AGCU"
#' 
#' @export
transcribe <- function(ss) {
    .Call(`_biox_transcribe`, ss)
}

#' translation, from RNA to AA
#' @examples
#' transcribe("AGCU") # "AGCU"
#' 
#' @export
translate <- function(ss, offset = 0L) {
    .Call(`_biox_translate`, ss, offset)
}

#' @export
tm <- function(ss) {
    .Call(`_biox_tm`, ss)
}

