# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_biox_rcpp_hello_world`)
}

rdna <- function(n = 1L, l = 20L) {
    .Call(`_biox_rdna`, n, l)
}

rrna <- function(n = 1L, l = 20L) {
    .Call(`_biox_rrna`, n, l)
}

#' reverse complement seq
#' @param ss seq vectors
#' @examples
#' revcom(c("AGCT", "AAAA"))
#' 
#' @export
revcomp <- function(ss) {
    .Call(`_biox_revcomp`, ss)
}

#' kmers
#' @param s seq
#' @param k kmer size
#' @examples
#' kmers("AGCTTTTTTTTT")
#' kmers("AGCTTTTTTTTT", 4)
#' 
#' @export
#' 
kmers <- function(s, k = 3L) {
    .Call(`_biox_kmers`, s, k)
}

